export function handleError(error) {}

export function handleSuccess(res) {}
